pipeline {
    agent any
    stages {
        stage ("Test"){
            steps {
                echo "Test Hello World!"
            }
        }
        stage ("stage 2"){
            steps {
                echo "Hello Jack! Welcome to Beijing !"
            }
        }
        stage ("Deploy"){
            steps {
                echo "Hello Jack! Welcome to Deploy Process !"
            }
        }
        stage ("Pass"){
            steps {
                echo "Hello Jack! You can leave the office now ~~~"
            }
        }
    }
}
