pipeline {
    agent any
    stages {
        stage ("stage 1"){
            steps {
                echo "Hello World! 12345678910"
            }
        }
        stage ("stage 2"){
            steps {
                echo "Hello Jack! Welcome to Beijing !"
            }
        }
    }
}
