name: Do anything after the release of the first workflow

on:
  workflow_run:
    workflows: ["Build"]
    types: [requested, completed]
    branches:
      - main
      - 'releases/**'
      - '!releases/**-alpha'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: triggrt_another_workflow
        run: echo successfully trigger ${{ github.workflow.name }}.
