name: test-call-api

on:
  workflow_dispatch:
    inputs:
      ARTIFACT_NAME:
        type: string
        required: true 
        
jobs:
  package_artifact:
    runs-on: ubuntu-latest
    steps:
    - name: print ARTIFACT_NAME
      run: echo ${{ inputs.ARTIFACT_NAME }}
        
