name: test-artifact

on:
  workflow_dispatch:
  
jobs:
  package_artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: check folder
      run: |
        pwd && ls -al
        echo $date >> date.json
        mkdir -p fruit/apple
        mkdir -p fruit/banana
        zip -r apple.zip fruit/apple
        zip -r banana.zip fruit/banana
    - name: zip folder
      run: |
        zip -r test.zip .github/
        zip date.json.zip date.json 
    
    - name: Upload  files
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: |
          #.github
          #test.zip
          fruit/apple
          fruit/banana
          date.json
  download_artifact:
    runs-on: ubuntu-latest
    needs: ["package_artifact"]
    steps:
    - name: Download files
      uses: actions/download-artifact@v3
      with:
        name: artifact
            
    - name: check folder
      run: |
        pwd && ls -al
        
    - name: Unzip
      run: |
        unzip apple.zip  
        unzip banana.zip
        ls -al
        cd fruit
        ls -al
        
    - name: create folder
      run: |
        pwd && ls -al
