name: test-matriax

on:
  workflow_dispatch:
  
jobs:
  read_file_job:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.read_file.outputs.matrix }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read File
      working-directory: .github/workflows
      id: read_file
      run: |
        # Read the file and store its content in a variable
        temp=$(echo '{"version": ["1.1.1", "2.2.2"]}' | jq -r '.version')
        echo "matrix="$temp"" >> $GITHUB_OUTPUT
        #echo "::set-output name=file_content::$TTT"
        #echo "::set-output name=TTT::$TTT"
        #file_content=$(cat test.json | jq -c '.version')
        #echo $file_content
        #echo "::set-output name=file_content::$(echo ${file_content}"

  use_matrix_job:
    runs-on: ubuntu-latest
    needs: [read_file_job]
    strategy:
      matrix:
        version: ${{ needs.read_file_job.outputs.matrix }}"
    steps:
    - name: Print Matrix Value
      run: |
        echo "Matrix Value: ${{ matrix.version }}"
