name: test-output

on:
  workflow_dispatch:

        
jobs:
  output_print:
    runs-on: ubuntu-latest
    steps:
    - name: Check folder
      run: ls -al
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Get Failed
      id: get_filename
      run: |
        ls -al
        chmod +x .github/workflows/scripts.sh
    - name: print output
      run: echo ${{ steps.get_filename.outputs.stdout }}"
        
